# Generated by Django 5.0.1 on 2024-08-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommenderinfo',
            name='stage',
            field=models.CharField(choices=[('description', 'Description'), ('status', 'Status'), ('hours', 'Hours'), ('resources', 'Resources'), ('computers', 'Computers'), ('strengths', 'Strengths'), ('weakness', 'Weakness'), ('team', 'Team'), ('interests', 'Interests'), ('academics', 'Academics'), ('exposure', 'Exposure'), ('motivation', 'Motivation'), ('thankyou', 'ThankYou')], default='learner', max_length=100),
        ),
        migrations.AlterField(
            model_name='recommenderinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
