# Generated by Django 5.0.1 on 2024-08-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0002_profile_is_onboarded_recommenderinfo_stage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommenderinfo',
            old_name='sender',
            new_name='profile',
        ),
    ]
