# Generated by Django 5.0.1 on 2024-08-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0003_rename_sender_recommenderinfo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommenderinfo',
            name='computers',
            field=models.TextField(blank=True),
        ),
    ]
