# Generated by Django 5.0.1 on 2024-08-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0004_alter_recommenderinfo_computers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('', ''), ('learner', 'Learner'), ('mentor', 'Mentor')], default='', max_length=100),
        ),
    ]
