# Generated by Django 5.0.1 on 2024-08-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0005_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenderinfo',
            name='computers_level',
            field=models.IntegerField(default=0),
        ),
    ]
