# Generated by Django 5.0.1 on 2024-08-08 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0006_recommenderinfo_computers_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Design', 'Design'), ('Management', 'Management'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Development', 'Development'), ('Data', 'Data'), ('Quality Assurance', 'Quality Assurance'), ('Cloud', 'Cloud'), ('IT & Operations', 'IT & Operations')], default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility', models.IntegerField()),
                ('revealed', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='compasaiv2_app.profile')),
                ('suggested_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_skill', to='compasaiv2_app.skill')),
            ],
        ),
    ]
