# Generated by Django 5.0.1 on 2024-08-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0007_skill_myprofileskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofileskill',
            old_name='compatibility',
            new_name='ranking',
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Creative', 'Creative'), ('Product', 'Product'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Engineering', 'Engineering'), ('Data', 'Data'), ('Operations', 'Operations')], default=None, max_length=100),
        ),
    ]
