# Generated by Django 5.0.1 on 2024-08-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0008_rename_compatibility_myprofileskill_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofileskill',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myprofileskill',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.TextField(blank=True),
        ),
    ]
