# Generated by Django 5.0.1 on 2024-08-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0010_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
