# Generated by Django 5.0.1 on 2024-08-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0012_profile_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.TextField(blank=True),
        ),
    ]
