# Generated by Django 5.0.1 on 2024-08-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0013_profile_education_profile_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skills',
            new_name='strengths',
        ),
    ]
