# Generated by Django 5.0.1 on 2024-08-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0014_rename_skills_profile_strengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(default=list, null=True),
        ),
    ]
