# Generated by Django 5.0.1 on 2024-08-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0015_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofileskill',
            name='recommended',
            field=models.BooleanField(default=True),
        ),
    ]
