# Generated by Django 5.0.1 on 2024-08-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0017_profile_mentor_skills_alter_profile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
