# Generated by Django 5.0.1 on 2024-08-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0022_alter_profile_user_type_conversation_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.AddField(
            model_name='message',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='compasaiv2_app.profile'),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
