# Generated by Django 5.0.1 on 2024-08-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0023_remove_message_conversation_message_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='archived',
            field=models.ManyToManyField(blank=True, related_name='archived_users', to='compasaiv2_app.profile'),
        ),
    ]
