# Generated by Django 5.0.1 on 2024-08-31 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0024_profile_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='archived',
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('messages', models.ManyToManyField(blank=True, related_name='messages', to='compasaiv2_app.message')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to='compasaiv2_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='compasaiv2_app.conversation'),
        ),
    ]
