# Generated by Django 5.0.1 on 2024-08-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0025_remove_message_participants_remove_profile_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
