# Generated by Django 5.0.1 on 2024-09-02 11:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0026_conversation_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='compasaiv2_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to='compasaiv2_app.profile')),
                ('participants', models.ManyToManyField(blank=True, related_name='group_participants', to='compasaiv2_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='compasaiv2_app.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_sender', to='compasaiv2_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='group_messages', to='compasaiv2_app.groupmessage'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
                ('comments', models.ManyToManyField(blank=True, related_name='post_comments', to='compasaiv2_app.comment')),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to='compasaiv2_app.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compasaiv2_app.profile')),
                ('images', models.ManyToManyField(blank=True, related_name='post_images', to='compasaiv2_app.postimage')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ManyToManyField(blank=True, related_name='community_member', to='compasaiv2_app.profile')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compasaiv2_app.skill')),
                ('groups', models.ManyToManyField(blank=True, related_name='community_group', to='compasaiv2_app.group')),
                ('posts', models.ManyToManyField(blank=True, related_name='community_post', to='compasaiv2_app.post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='compasaiv2_app.post'),
        ),
    ]
