# Generated by Django 5.0.1 on 2024-09-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0027_postimage_comment_group_groupmessage_group_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='compasaiv2_app.community'),
        ),
    ]
