# Generated by Django 5.0.1 on 2024-09-03 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0028_post_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='Group',
            new_name='group',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='project_images')),
                ('tasks', models.JSONField(blank=True, default=list, null=True)),
                ('scenario', models.TextField()),
                ('duration', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='compasaiv2_app.profile')),
                ('participants', models.ManyToManyField(blank=True, related_name='project_participants', to='compasaiv2_app.profile')),
            ],
        ),
    ]
