# Generated by Django 5.0.1 on 2024-09-03 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0029_rename_group_groupmessage_group_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compasaiv2_app.skill'),
        ),
    ]
