# Generated by Django 5.0.1 on 2024-09-04 00:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0030_project_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_rating', models.IntegerField(default=0)),
                ('review_date', models.DateTimeField(default=datetime.datetime.now)),
                ('review_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to='compasaiv2_app.profile')),
                ('review_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sub', to='compasaiv2_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('post_link', models.TextField()),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='compasaiv2_app.community')),
                ('images', models.ManyToManyField(blank=True, related_name='submission_images', to='compasaiv2_app.postimage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compasaiv2_app.profile')),
                ('reviews', models.ManyToManyField(blank=True, related_name='submission_reviews', to='compasaiv2_app.review')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='project_submissions', to='compasaiv2_app.submission'),
        ),
    ]
