# Generated by Django 5.0.1 on 2024-09-04 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0031_review_submission_project_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='community',
        ),
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='compasaiv2_app.project'),
        ),
    ]
