# Generated by Django 5.0.1 on 2024-09-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0032_remove_submission_community_submission_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sub', to='compasaiv2_app.submission'),
        ),
    ]
