# Generated by Django 5.0.1 on 2024-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0033_alter_review_review_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
        ),
    ]
