# Generated by Django 5.0.1 on 2024-09-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0034_alter_review_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roadmap',
            field=models.JSONField(blank=True, default=[{'level': 'BEGINNER', 'sections': [{'duration': '2', 'id': 1, 'progress': 5, 'tasks': [{'description': 'Click here to start a crash course. This will help you get started in this career path.', 'name': 'Intro Course', 'status': 'done', 'sub_id': 1}, {'description': '', 'name': 'Intro Quiz', 'status': 'pending', 'sub_id': 2}, {'description': '', 'name': 'Your Expectations', 'status': 'pending', 'sub_id': 3}], 'title': 'INTRODUCTION'}, {'duration': '6', 'id': 2, 'progress': 55, 'tasks': [{'description': 'Spend minimum of 2 hours weekly on a course. ', 'name': 'Beginner Course', 'status': 'pending', 'sub_id': 1}, {'description': 'What did you learn from this course?', 'name': 'Course Lesson', 'status': 'pending', 'sub_id': 2}], 'title': 'LEARNING'}, {'duration': '2', 'id': 3, 'progress': 0, 'tasks': [{'description': 'Work on a beginner project', 'name': 'Project Submission', 'status': 'pending', 'sub_id': 1}, {'description': 'Work on a beginner project', 'name': 'Portfolio Setup', 'status': 'pending', 'sub_id': 2}], 'title': 'PRACTICE'}, {'duration': '1', 'id': 4, 'progress': 0, 'tasks': [{'description': 'Work on a beginner project', 'name': 'Book Mentorship', 'status': 'pending', 'sub_id': 1}], 'title': 'NETWORK'}], 'startdate': '2024-03-25'}, {'level': 'INTERMEDIATE', 'sections': [{'duration': '15', 'id': 5, 'progress': 0, 'tasks': [{'description': 'Build for the public', 'name': 'Open source project', 'status': 'done', 'sub_id': 1}, {'description': 'Apply for internship roles', 'name': 'Internship', 'status': 'pending', 'sub_id': 2}, {'description': 'Speak to a mentor', 'name': 'Share Experience', 'status': 'pending', 'sub_id': 3}], 'title': 'APPLICATION'}], 'startdate': '2024-09-01'}, {'level': 'PROFESSIONAL', 'sections': [{'duration': '8', 'id': 6, 'progress': 0, 'tasks': [{'description': 'Spend minimum of 2 hours weekly on a course. ', 'name': 'Start Adavanced Beginner Course', 'status': 'pending', 'sub_id': 1}, {'description': 'What did you learn from this course?', 'name': 'Course Lesson', 'status': 'pending', 'sub_id': 2}], 'title': 'ADVANCED LEARNING'}, {'duration': '2', 'id': 7, 'progress': 0, 'tasks': [{'description': 'Spend minimum of 2 hours weekly on a course. ', 'name': 'Publication Release', 'status': 'pending', 'sub_id': 1}, {'description': 'What did you learn from this course?', 'name': 'Certification', 'status': 'pending', 'sub_id': 2}], 'title': 'RECOGNITION'}, {'duration': '4', 'id': 8, 'progress': 0, 'tasks': [{'description': 'Spend minimum of 2 hours weekly on a course. ', 'name': 'Mock Interviews', 'status': 'pending', 'sub_id': 1}, {'description': 'What did you learn from this course?', 'name': 'Job Applications', 'status': 'pending', 'sub_id': 2}], 'title': 'JOB READY'}], 'startdate': '2024-09-01'}], null=True),
        ),
    ]
