# Generated by Django 5.0.1 on 2024-09-06 12:04

import compasaiv2_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0035_profile_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roadmap',
            field=models.JSONField(blank=True, default=compasaiv2_app.models.default_roadmap, null=True),
        ),
    ]
