# Generated by Django 5.0.1 on 2024-09-06 16:34

import compasaiv2_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0036_alter_profile_roadmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roadmap',
        ),
        migrations.AddField(
            model_name='myprofileskill',
            name='roadmap',
            field=models.JSONField(blank=True, default=compasaiv2_app.models.default_roadmap, null=True),
        ),
    ]
