# Generated by Django 5.0.1 on 2024-09-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0037_remove_profile_roadmap_myprofileskill_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, choices=[('', ''), ('coffee_chat', 'coffee_chat'), ('office_hours', 'office_hours'), ('speed_networking', 'speed_networking'), ('mock_interview', 'mock_interview'), ('check_ins', 'check_ins')], default='', max_length=100)),
                ('date_time', models.JSONField(default=list)),
                ('note', models.TextField()),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_learner', to='compasaiv2_app.profile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_mentor', to='compasaiv2_app.profile')),
            ],
        ),
    ]
