# Generated by Django 5.0.1 on 2024-09-11 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0040_alter_profile_mentor_booking_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorship',
            name='conversation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='session_conversation', to='compasaiv2_app.conversation'),
            preserve_default=False,
        ),
    ]
