# Generated by Django 5.0.1 on 2024-09-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0043_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='message_images', to='compasaiv2_app.postimage'),
        ),
    ]
