# Generated by Django 5.0.1 on 2024-09-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0045_remove_group_messages_remove_group_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
