# Generated by Django 5.0.1 on 2024-09-13 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0046_group_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compasaiv2_app.skill'),
        ),
    ]
