# Generated by Django 5.0.1 on 2024-09-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0047_group_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='office_hour',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to='compasaiv2_app.profile'),
        ),
    ]
