# Generated by Django 5.0.1 on 2024-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0048_group_is_office_group_office_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
