# Generated by Django 5.0.1 on 2024-09-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0051_group_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
