# Generated by Django 5.0.1 on 2024-09-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0052_group_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='removed',
            field=models.ManyToManyField(blank=True, related_name='removed_participants', to='compasaiv2_app.profile'),
        ),
    ]
