# Generated by Django 5.0.1 on 2024-09-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0053_conversation_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='event',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(blank=True, choices=[('event', 'Event'), ('text', 'Text')], default='text', max_length=100),
        ),
    ]
