# Generated by Django 5.0.1 on 2024-09-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0054_message_event_message_msg_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='events',
        ),
    ]
