# Generated by Django 5.0.1 on 2024-09-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0056_remove_profile_mentor_skills_profile_mentor_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_office',
        ),
        migrations.RemoveField(
            model_name='group',
            name='office_hour',
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('time_slots', models.TextField(blank=True)),
                ('next_schedule', models.JSONField(default=dict)),
                ('schedule', models.JSONField(default=list)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='offcie_images')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_admin', to='compasaiv2_app.profile')),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_onversation', to='compasaiv2_app.conversation')),
                ('path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compasaiv2_app.skill')),
            ],
        ),
    ]
