# Generated by Django 5.0.1 on 2024-09-24 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0057_remove_group_is_office_remove_group_office_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mentor_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_skill', to='compasaiv2_app.skill'),
        ),
    ]
