# Generated by Django 5.0.1 on 2024-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0059_alter_profile_referred_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referred_profiles',
            field=models.ManyToManyField(blank=True, related_name='referred_users', to='compasaiv2_app.profile'),
        ),
    ]
