# Generated by Django 5.0.1 on 2024-09-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0060_alter_profile_referred_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', ''), ('explorer', 'explorer'), ('seeker', 'seeker'), ('advancer', 'advancer'), ('mentor', 'Mentor')], default='', max_length=100),
        ),
    ]
