# Generated by Django 5.0.1 on 2024-09-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0061_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', ''), ('explorer', 'Explorer'), ('seeker', 'Seeker'), ('advancer', 'Advancer'), ('mentor', 'Mentor')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recommenderinfo',
            name='stage',
            field=models.CharField(choices=[('description', 'Description'), ('status', 'Status'), ('career', 'Career'), ('hours', 'Hours'), ('resources', 'Resources'), ('computers', 'Computers'), ('strengths', 'Strengths'), ('weakness', 'Weakness'), ('team', 'Team'), ('interests', 'Interests'), ('academics', 'Academics'), ('exposure', 'Exposure'), ('motivation', 'Motivation'), ('thankyou', 'ThankYou')], default='learner', max_length=100),
        ),
    ]
