# Generated by Django 5.0.1 on 2024-09-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0062_alter_profile_user_type_alter_recommenderinfo_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommenderinfo',
            name='stage',
            field=models.CharField(choices=[('contact', 'Contact'), ('description', 'Description'), ('status', 'Status'), ('career', 'Career'), ('hours', 'Hours'), ('resources', 'Resources'), ('computers', 'Computers'), ('strengths', 'Strengths'), ('weakness', 'Weakness'), ('team', 'Team'), ('interests', 'Interests'), ('academics', 'Academics'), ('exposure', 'Exposure'), ('motivation', 'Motivation'), ('thankyou', 'ThankYou')], default='learner', max_length=100),
        ),
    ]
