# Generated by Django 5.0.1 on 2024-09-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0064_alter_recommenderinfo_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenderinfo',
            name='career',
            field=models.TextField(blank=True),
        ),
    ]
