# Generated by Django 5.0.1 on 2024-09-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0066_recommenderinfo_career_next_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommenderinfo',
            name='career',
        ),
        migrations.RemoveField(
            model_name='recommenderinfo',
            name='career_next_steps',
        ),
        migrations.RemoveField(
            model_name='recommenderinfo',
            name='career_proficiency',
        ),
        migrations.RemoveField(
            model_name='recommenderinfo',
            name='career_skills',
        ),
        migrations.AlterField(
            model_name='recommenderinfo',
            name='stage',
            field=models.CharField(choices=[('contact', 'Contact'), ('description', 'Description'), ('status', 'Status'), ('hours', 'Hours'), ('resources', 'Resources'), ('computers', 'Computers'), ('strengths', 'Strengths'), ('weakness', 'Weakness'), ('team', 'Team'), ('interests', 'Interests'), ('academics', 'Academics'), ('exposure', 'Exposure'), ('motivation', 'Motivation'), ('thankyou', 'ThankYou')], default='contact', max_length=100),
        ),
    ]
