# Generated by Django 5.0.1 on 2024-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0067_remove_recommenderinfo_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes'),
        ),
        migrations.AlterField(
            model_name='recommenderinfo',
            name='stage',
            field=models.CharField(choices=[('contact', 'Contact'), ('description', 'Description'), ('status', 'Status'), ('hours', 'Hours'), ('resources', 'Resources'), ('computers', 'Computers'), ('strengths', 'Strengths'), ('weakness', 'Weakness'), ('team', 'Team'), ('interests', 'Interests'), ('academics', 'Academics'), ('exposure', 'Exposure'), ('motivation', 'Motivation'), ('resume', 'Resume'), ('thankyou', 'ThankYou')], default='contact', max_length=100),
        ),
    ]
