# Generated by Django 5.0.1 on 2024-09-30 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0069_alter_myprofileskill_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, choices=[('', ''), ('coffee_chat', 'coffee_chat'), ('office_hours', 'office_hours'), ('speed_networking', 'speed_networking'), ('mock_interview', 'mock_interview'), ('check_ins', 'check_ins')], default='', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('start_date', models.DateField(default='')),
                ('end_date', models.DateField(default='')),
                ('times', models.JSONField(default=dict)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_session_mentor', to='compasaiv2_app.profile')),
            ],
        ),
    ]
