# Generated by Django 5.0.1 on 2024-09-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0070_mentorshipsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipsession',
            name='end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentorshipsession',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
