# Generated by Django 5.0.1 on 2024-10-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0074_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='learner_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='learner_rating',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='mentor_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mentor_rating',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('upcoming', 'Upcoming'), ('pending', 'Pending'), ('reschedule', 'Reschedule'), ('past', 'Past'), ('cancelled', 'Cancelled')], default='upcoming', max_length=100),
        ),
    ]
