# Generated by Django 5.0.1 on 2024-10-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0075_booking_learner_feedback_booking_learner_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mentor_skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='mentor_skill',
            field=models.ManyToManyField(blank=True, related_name='mentor_skill', to='compasaiv2_app.skill'),
        ),
    ]
