# Generated by Django 5.0.1 on 2024-10-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0076_remove_profile_mentor_skill_profile_mentor_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mentor_skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='mentor_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_skill', to='compasaiv2_app.skill'),
        ),
    ]
