# Generated by Django 5.0.1 on 2024-10-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0078_mentorshipsession_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='log',
            field=models.JSONField(default=list),
        ),
    ]
