# Generated by Django 5.0.1 on 2024-10-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0079_booking_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('reschedule', 'Reschedule'), ('past', 'Past'), ('cancelled', 'Cancelled')], default='upcoming', max_length=100),
        ),
    ]
