# Generated by Django 5.0.1 on 2024-10-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasaiv2_app', '0080_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='learner_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='mentor_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
