from django.contrib import admin
from django.urls import path, include
from . import views 
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('onboarding', views.onboarding, name='onboarding'),
    path('activate/<str:uidb64>/<str:token>',views.activate, name='activate'),
    path('login', views.login, name='login'),
    path('set_password', views.set_password, name='set_password'),
    path('confirm_email/<str:email>', views.confirm_email, name='confirm_email'),
    path('logout', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/edit_profile/', views.profile_edit_bio, name='profile_edit'),
    path('<str:username>/edit_profile_skills/', views.profile_edit_skills, name='profile_edit_skills'),
    path('<str:username>/edit_profile_links/', views.profile_edit_links, name='profile_edit_links'),
    path('<str:username>/edit_profile_education/', views.profile_edit_education, name='profile_edit_education'),
    path('<str:username>/edit_profile_experience/', views.profile_edit_experience, name='profile_edit_experience'),
    path('<str:username>/edit_profile_settings/', views.profile_edit_settings, name='profile_edit_settings'),
    path('recommendation', views.recommendation, name='recommendation'),
    path('<str:username>/paths/<str:skill>', views.profile_paths_view, name='paths_view'),
    path('<str:username>/projects/', views.profile_projects, name='profile_projects'),
    path('<str:username>/paths/', views.profile_paths, name='profile_paths'),
    path('<str:username>/skills/', views.profile_skills, name='profile_skills'),
    path('<str:username>/book-session/', views.book_session, name='book_session'),
    path('connect', views.connect, name='connect'),
    path('connect_peers', views.connect_peers, name='connect_peers'),
    path('connect_mentors', views.connect_mentors, name='connect_mentors'),
    path('connect_all', views.connect_all, name='connect_all'),
    path('path', views.path, name='path'),
    path('path/<str:skill_name>', views.path_detail, name='path_detail'),
    path('path/<str:skill_name>/courses', views.path_courses, name='path_courses'),
    path('path/<str:skill_name>/mentors', views.path_mentors, name='path_mentors'),
    path('path/<str:skill_name>/projects', views.path_projects, name='path_projects'),
    path('messages', views.messaging, name='messages'),
    path('message/<str:username>', views.message, name='message'),
    path('message/<str:group>/<str:username>', views.message, name='message'),
    path('community', views.community, name='community'),
    path('community/post/<slug:slug>/', views.view_post, name='view_post'),
    path('project', views.project, name='project'),
    path('project/add-new', views.project_add, name='project_add'),
    path('project/edit/<int:project_id>', views.project_edit, name='project_edit'),
    path('project/<int:project_id>', views.project_detail, name='project_detail'),
    path('progress', views.task_progress, name='progress'),
    path('roadmap', views.roadmap, name='roadmap'),
    path('roadmap/<int:id>', views.roadmap_detail, name='roadmap_detail'),
    path('course_detail', views.course_detail, name='course_detail'),
    path('terms_of_service', views.terms_and_conditions, name='terms_and_conditions'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('check-email', views.check_email_exists, name='check_email_exists'),
    path('<str:username>/update_profile_images', views.update_profile_images, name='update_profile_images'),
    path('<str:username>/edit_profile/update_profile_data', views.update_profile_data, name='update_profile_data'),
    path('<str:username>/edit_profile_skills/update_profile_data', views.update_profile_data, name='update_profile_data'),
    path('<str:username>/edit_profile_links/update_profile_data', views.update_profile_data, name='update_profile_data'),
    path('<str:username>/edit_profile_education/update_profile_data', views.update_profile_data, name='update_profile_data'),
    path('<str:username>/edit_profile_experience/update_profile_data', views.update_profile_data, name='update_profile_data'),
    path('<str:username>/paths/', views.remove_overlay, name='remove_overlay'),
    path('<str:username>/paths/<str:skill>/enrol_path_loader/', views.enrol_path_loader, name='enrol_path_loader'),
    path('<str:username>/paths/<str:skill>/enrol_path/', views.enrol_path, name='enrol_path'),
    path('connect', views.remove_overlay_book, name='remove_overlay_book'),
    path('follow/<str:username>/', views.follow, name='follow'),
    path('<str:username>/follow', views.follow, name='follow'),
    path('archived', views.archived, name='archived'),
    path('all_messages', views.all_messages, name='all_messages'),
    path('archive_message/<str:username>', views.archive_message, name='archive_message'),
    path('delete_message/<str:username>', views.delete_message, name='delete_message'),
    path('clear_unread', views.clear_unread, name='clear_unread'),
    path('new_chat', views.new_chat, name='new_chat'),
    path('new_post', views.new_post, name='new_post'),
    path('like_post', views.like_post, name='like_post'),
    path('comment_post', views.comment_post, name='comment_post'),
    path('create_project', views.create_project, name='create_project'),
    path('update_project', views.update_project, name='update_project'),
    path('new_submission', views.new_submission, name='new_submission'),
    path('new_submission_update', views.new_submission_update, name='new_submission_update'),
    path('leavereview', views.leavereview, name='leavereview'),
    path('mark_task', views.mark_task, name='mark_task'),
    path('joinproject/<int:id>', views.joinproject, name='joinproject'),
    path('view_calendar', views.view_calendar, name='view_calendar'),
    path('confirm_booking', views.confirm_booking, name='confirm_booking'),
    path('delete_post', views.delete_post, name='delete_post'),
    path('remove_participant/<str:group>/<str:username>', views.remove_participant, name='remove_participant'),
    path('add_participant/<str:group>/<str:username>', views.add_participant, name='add_participant'),
    path('create_group', views.create_group, name='create_group'),
    
    


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)